# Copyright © 2024, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

name: pushiomanager_flutter
description: Flutter plugin for Responsys Mobile SDK

version: 7.0.0
repository: https://github.com/oracle-samples/pushiomanager-flutter

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pushio.manager.flutter
        pluginClass: PushIOManagerFlutterPlugin
      ios:
        pluginClass: PushIOManagerFlutterPlugin
